#!/bin/bash
# Configuration (template)
# copy to config.sh and enter values

SHEDS_CLSB_DB_HOST=""
SHEDS_CLSB_DB_PORT=5432
SHEDS_CLSB_DB_USER=""
SHEDS_CLSB_DB_PASSWORD=""
SHEDS_CLSB_DB_DBNAME=""

SHEDS_CLSB_TILES_DIR=""

SHEDS_CLSB_DB_CONNSTRING="host=$SHEDS_CLSB_DB_HOST port=$SHEDS_CLSB_DB_PORT user=$SHEDS_CLSB_DB_USER dbname=$SHEDS_CLSB_DB_DBNAME"
